//! Routes saved as JSON, and the addon's data files.

use crate::export::{self, Route};
use crate::model::Names;
use anyhow::Result;
use rusqlite::Connection;
use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

/// Every saved route.
pub fn load_routes(routes_dir: &Path) -> Result<Vec<Route>> {
    let mut files: Vec<_> = match std::fs::read_dir(routes_dir) {
        Ok(dir) => dir
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "json"))
            .collect(),
        Err(_) => Vec::new(),
    };
    files.sort();
    Ok(files
        .iter()
        .filter_map(|f| export::read_route(serde_json::from_str(&std::fs::read_to_string(f).ok()?).ok()?).ok())
        .collect())
}

pub fn save_route(routes_dir: &Path, route: &Route) -> Result<()> {
    std::fs::create_dir_all(routes_dir)?;
    let path = routes_dir.join(format!("{}.json", slug(&route.name)));
    std::fs::write(&path, serde_json::to_string_pretty(route)?)?;
    Ok(())
}

/// Regenerate the addon's Routes.lua from every saved route, each written in its own language.
pub fn write_addon_routes(conn: &Connection, routes_dir: &Path, addon_dir: &Path) -> Result<usize> {
    let routes = render_routes(conn, &load_routes(routes_dir)?, None)?;
    std::fs::write(addon_dir.join("Routes.lua"), export::to_lua(&routes))?;
    Ok(routes.len())
}

/// Routes written in `locale` (None: each in the language it was made in), the names of each
/// language read once from the database.
pub fn render_routes(conn: &Connection, routes: &[Route], locale: Option<&str>) -> Result<Vec<Route>> {
    let mut names: HashMap<String, Names> = HashMap::new();
    routes
        .iter()
        .map(|r| {
            let locale = locale.or(r.locale.as_deref()).unwrap_or("enUS").to_owned();
            if !names.contains_key(&locale) {
                names.insert(locale.clone(), Names::load(conn, &locale)?);
            }
            Ok(export::render(r, &names[&locale]))
        })
        .collect()
}

/// Write the addon's Config.lua from the app's addon settings (flat key -> bool/number/string).
pub fn write_addon_config(addon_dir: &Path, config: &serde_json::Map<String, serde_json::Value>) -> Result<()> {
    let mut out = String::from("-- Generated by the Factoruide app. Do not edit.\nlocal _, FG = ...\nFG.Config = {\n");
    let mut keys: Vec<_> = config.keys().collect();
    keys.sort();
    for key in keys {
        let value = match &config[key] {
            serde_json::Value::Bool(b) => b.to_string(),
            serde_json::Value::Number(n) => n.to_string(),
            serde_json::Value::String(s) => format!("{s:?}"),
            _ => continue,
        };
        if key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            let _ = writeln!(out, "    {key} = {value},");
        }
    }
    out.push_str("}\n");
    std::fs::write(addon_dir.join("Config.lua"), out)?;
    Ok(())
}

/// Lowercase ASCII identifier of a name, for file names ("Mon guide Nain !" -> "mon-guide-nain").
pub fn slug(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars().flat_map(char::to_lowercase) {
        let c = match c {
            'à' | 'á' | 'â' | 'ã' | 'ä' | 'å' => 'a',
            'ç' => 'c',
            'è' | 'é' | 'ê' | 'ë' => 'e',
            'ì' | 'í' | 'î' | 'ï' => 'i',
            'ñ' => 'n',
            'ò' | 'ó' | 'ô' | 'õ' | 'ö' => 'o',
            'ù' | 'ú' | 'û' | 'ü' => 'u',
            'ý' | 'ÿ' => 'y',
            c => c,
        };
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else if !out.is_empty() && !out.ends_with('-') {
            out.push('-');
        }
    }
    let out = out.trim_end_matches('-').to_owned();
    if out.is_empty() { "route".into() } else { out }
}
