//! The addon's data file: every route as Lua tables.

use super::types::Route;
use std::fmt::Write as _;

fn lua_str(s: &str) -> String {
    format!("{s:?}")
}

/// Lua data file for the addon, holding every given route.
pub fn to_lua(routes: &[Route]) -> String {
    let mut out =
        String::from("-- Generated by `fg route`. Do not edit.\nlocal _, FG = ...\nFG.Routes = FG.Routes or {}\n");
    for r in routes {
        let _ = writeln!(
            out,
            "FG.Routes[{}] = {{ race = {}, class = {}, faction = {}, locale = {}, fromLevel = {}, toLevel = {}, time = {}, levels = {{ {} }}, professions = {{ {} }}, spells = {{ {} }}, checkpoints = {{ {} }}, steps = {{",
            lua_str(&r.name),
            r.race_id,
            r.class_id,
            lua_str(r.faction.name()),
            lua_str(r.locale.as_deref().unwrap_or("enUS")),
            r.from_level,
            r.to_level,
            r.total_time,
            // Planned play time (seconds) on reaching each level: [level] = time.
            (r.from_level + 1..=r.to_level)
                .filter_map(|l| r
                    .steps
                    .iter()
                    .find(|s| s.level >= l)
                    .map(|s| format!("[{l}] = {}", s.time.round())))
                .collect::<Vec<_>>()
                .join(", "),
            r.professions
                .iter()
                .map(|p| format!(
                    "{{ key = {}, name = {}, line = {}, target = {}, start = {}, curve = {{ {} }} }}",
                    lua_str(&p.key),
                    lua_str(&p.name),
                    p.skill_line,
                    p.target,
                    p.start,
                    p.curve.iter().map(ToString::to_string).collect::<Vec<_>>().join(", ")
                ))
                .collect::<Vec<_>>()
                .join(", "),
            r.spells.iter().map(ToString::to_string).collect::<Vec<_>>().join(", "),
            // Lua indexes from 1.
            r.checkpoints
                .iter()
                .map(|c| format!("{{ lvl = {}, step = {} }}", c.level, c.step + 1))
                .collect::<Vec<_>>()
                .join(", ")
        );
        for s in &r.steps {
            let mut fields = vec![
                format!("k = {}", lua_str(s.kind.as_str())),
                format!("t = {}", lua_str(&s.text)),
            ];
            if let Some(q) = s.quest {
                fields.push(format!("q = {q}"));
            }
            if s.bg {
                fields.push("bg = true".into());
            }
            if !s.alt.is_empty() {
                fields.push(format!(
                    "alt = {{ {} }}",
                    s.alt.iter().map(ToString::to_string).collect::<Vec<_>>().join(", ")
                ));
            }
            if let Some(o) = s.objective {
                fields.push(format!("o = {}", o + 1));
            }
            if let Some(m) = &s.map {
                fields.push(format!("m = {}, x = {}, y = {}", m.ui_map, m.x, m.y));
            }
            if let Some(t) = &s.target {
                fields.push(format!(
                    "e = {}, id = {}, n = {}",
                    lua_str(t.kind.as_str()),
                    t.id,
                    lua_str(&t.name)
                ));
            }
            if let Some(sk) = s.skill {
                fields.push(format!("sk = {sk}"));
            }
            if let Some(line) = s.line {
                fields.push(format!("line = {line}"));
            }
            if s.elite {
                fields.push("el = true".into());
            }
            if let Some(l) = s.mob_level {
                fields.push(format!("ml = {l}"));
            }
            if !s.mobs.is_empty() {
                fields.push(format!(
                    "mobs = {{ {} }}",
                    s.mobs.iter().map(|m| lua_str(m)).collect::<Vec<_>>().join(", ")
                ));
            }
            if let Some(item) = s.reward {
                fields.push(format!("rw = {item}"));
            }
            if !s.spells.is_empty() {
                fields.push(format!(
                    "sp = {{ {} }}",
                    s.spells.iter().map(ToString::to_string).collect::<Vec<_>>().join(", ")
                ));
            }
            if s.keep {
                fields.push("kp = true".into());
            }
            fields.push(format!("lvl = {}", s.level));
            if let Some(xp) = s.xp {
                fields.push(format!("xp = {xp}"));
            }
            let _ = writeln!(out, "  {{ {} }},", fields.join(", "));
        }
        out.push_str("} }\n");
    }
    out
}
