-- Generated by `fg talents` from the game's talent trees. Do not edit.
-- One talent per level from 10: { tab, tier, column } (1-based, as GetTalentInfo).
local _, FG = ...
FG.TalentBuilds = FG.TalentBuilds or {}
FG.TalentBuilds.tbc = {
    WARRIOR = {
        spec = "Arms",
        picks = {
            { 1, 1, 1 }, -- Improved Heroic Strike
            { 1, 1, 1 }, -- Improved Heroic Strike
            { 1, 1, 1 }, -- Improved Heroic Strike
            { 3, 1, 2 }, -- Tactical Mastery
            { 3, 1, 2 }, -- Tactical Mastery
            { 3, 1, 2 }, -- Tactical Mastery
            { 1, 1, 3 }, -- Improved Rend
            { 1, 1, 3 }, -- Improved Rend
            { 1, 1, 3 }, -- Improved Rend
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 1, 2 }, -- Booming Voice
            { 2, 1, 2 }, -- Booming Voice
            { 2, 1, 2 }, -- Booming Voice
            { 2, 1, 2 }, -- Booming Voice
            { 2, 1, 2 }, -- Booming Voice
            { 1, 1, 2 }, -- Deflection
            { 1, 1, 2 }, -- Deflection
            { 1, 1, 2 }, -- Deflection
            { 1, 1, 2 }, -- Deflection
            { 1, 3, 1 }, -- Improved Overpower
            { 1, 3, 1 }, -- Improved Overpower
            { 1, 3, 2 }, -- Anger Management
            { 1, 3, 3 }, -- Deep Wounds
            { 1, 3, 3 }, -- Deep Wounds
            { 1, 3, 3 }, -- Deep Wounds
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 3 }, -- Impale
            { 1, 4, 3 }, -- Impale
            { 1, 1, 2 }, -- Deflection
            { 1, 2, 1 }, -- Improved Charge
            { 1, 2, 1 }, -- Improved Charge
            { 1, 2, 2 }, -- Iron Will
            { 1, 2, 2 }, -- Iron Will
            { 1, 2, 2 }, -- Iron Will
            { 1, 2, 2 }, -- Iron Will
            { 1, 2, 2 }, -- Iron Will
            { 1, 2, 3 }, -- Improved Thunder Clap
            { 1, 2, 3 }, -- Improved Thunder Clap
            { 1, 2, 3 }, -- Improved Thunder Clap
            { 1, 5, 1 }, -- Poleaxe Specialization
            { 1, 5, 1 }, -- Poleaxe Specialization
            { 1, 5, 1 }, -- Poleaxe Specialization
            { 1, 5, 1 }, -- Poleaxe Specialization
            { 1, 5, 1 }, -- Poleaxe Specialization
            { 1, 5, 2 }, -- Death Wish
            { 1, 7, 2 }, -- Mortal Strike
            { 1, 5, 3 }, -- Mace Specialization
            { 1, 5, 3 }, -- Mace Specialization
        },
    },
    PALADIN = {
        spec = "Retribution",
        picks = {
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 2, 1 }, -- Improved Judgement
            { 3, 2, 1 }, -- Improved Judgement
            { 3, 2, 2 }, -- Improved Seal of the Crusader
            { 3, 2, 2 }, -- Improved Seal of the Crusader
            { 3, 2, 2 }, -- Improved Seal of the Crusader
            { 3, 3, 3 }, -- Seal of Command
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 3, 1 }, -- Vindication
            { 3, 3, 1 }, -- Vindication
            { 3, 3, 1 }, -- Vindication
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 4 }, -- Pursuit of Justice
            { 3, 3, 4 }, -- Pursuit of Justice
            { 3, 5, 1 }, -- Two-Handed Weapon Specialization
            { 3, 5, 1 }, -- Two-Handed Weapon Specialization
            { 3, 5, 1 }, -- Two-Handed Weapon Specialization
            { 3, 5, 3 }, -- Sanctity Aura
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 7, 2 }, -- Repentance
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 3, 4 }, -- Pursuit of Justice
            { 3, 4, 1 }, -- Eye for an Eye
            { 3, 4, 1 }, -- Eye for an Eye
            { 3, 4, 3 }, -- Improved Retribution Aura
            { 3, 4, 3 }, -- Improved Retribution Aura
            { 3, 4, 4 }, -- Crusade
            { 3, 4, 4 }, -- Crusade
            { 3, 4, 4 }, -- Crusade
            { 3, 5, 4 }, -- Improved Sanctity Aura
            { 3, 5, 4 }, -- Improved Sanctity Aura
        },
    },
    HUNTER = {
        spec = "Beast Mastery",
        picks = {
            { 1, 1, 2 }, -- Improved Aspect of the Hawk
            { 1, 1, 2 }, -- Improved Aspect of the Hawk
            { 1, 1, 2 }, -- Improved Aspect of the Hawk
            { 1, 1, 2 }, -- Improved Aspect of the Hawk
            { 1, 1, 2 }, -- Improved Aspect of the Hawk
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 2, 3 }, -- Thick Hide
            { 1, 2, 3 }, -- Thick Hide
            { 1, 2, 3 }, -- Thick Hide
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 2, 4 }, -- Improved Revive Pet
            { 1, 2, 4 }, -- Improved Revive Pet
            { 1, 5, 1 }, -- Spirit Bond
            { 1, 5, 1 }, -- Spirit Bond
            { 1, 5, 2 }, -- Intimidation
            { 1, 5, 4 }, -- Bestial Discipline
            { 1, 5, 4 }, -- Bestial Discipline
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 7, 2 }, -- Bestial Wrath
            { 2, 1, 3 }, -- Lethal Shots
            { 2, 1, 3 }, -- Lethal Shots
            { 2, 1, 3 }, -- Lethal Shots
            { 2, 1, 3 }, -- Lethal Shots
            { 2, 1, 3 }, -- Lethal Shots
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 3, 3 }, -- Aimed Shot
            { 1, 2, 1 }, -- Focused Fire
            { 1, 2, 1 }, -- Focused Fire
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 3, 1 }, -- Pathfinding
            { 1, 3, 1 }, -- Pathfinding
            { 1, 3, 2 }, -- Bestial Swiftness
            { 1, 4, 2 }, -- Improved Mend Pet
            { 1, 4, 2 }, -- Improved Mend Pet
            { 1, 6, 1 }, -- Animal Handler
            { 1, 6, 1 }, -- Animal Handler
            { 1, 7, 1 }, -- Ferocious Inspiration
            { 1, 7, 1 }, -- Ferocious Inspiration
        },
    },
    ROGUE = {
        spec = "Combat",
        picks = {
            { 2, 1, 2 }, -- Improved Sinister Strike
            { 2, 1, 2 }, -- Improved Sinister Strike
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 1 }, -- Improved Slice and Dice
            { 2, 2, 1 }, -- Improved Slice and Dice
            { 2, 2, 1 }, -- Improved Slice and Dice
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 5, 3 }, -- Sword Specialization
            { 2, 5, 3 }, -- Sword Specialization
            { 2, 5, 3 }, -- Sword Specialization
            { 2, 5, 3 }, -- Sword Specialization
            { 2, 5, 3 }, -- Sword Specialization
            { 2, 5, 2 }, -- Blade Flurry
            { 2, 6, 2 }, -- Weapon Expertise
            { 2, 6, 2 }, -- Weapon Expertise
            { 2, 6, 3 }, -- Aggression
            { 2, 6, 3 }, -- Aggression
            { 2, 6, 3 }, -- Aggression
            { 2, 7, 2 }, -- Adrenaline Rush
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 2, 1 }, -- Ruthlessness
            { 1, 2, 1 }, -- Ruthlessness
            { 1, 2, 1 }, -- Ruthlessness
            { 1, 1, 1 }, -- Improved Eviscerate
            { 1, 1, 1 }, -- Improved Eviscerate
            { 1, 3, 1 }, -- Relentless Strikes
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 1, 1 }, -- Improved Eviscerate
            { 2, 1, 1 }, -- Improved Gouge
            { 2, 1, 1 }, -- Improved Gouge
            { 2, 1, 1 }, -- Improved Gouge
            { 2, 2, 2 }, -- Deflection
            { 2, 2, 2 }, -- Deflection
            { 2, 2, 2 }, -- Deflection
            { 2, 2, 2 }, -- Deflection
            { 2, 2, 2 }, -- Deflection
            { 2, 3, 1 }, -- Endurance
            { 2, 3, 1 }, -- Endurance
            { 2, 3, 2 }, -- Riposte
            { 2, 3, 4 }, -- Improved Sprint
        },
    },
    PRIEST = {
        spec = "Shadow",
        picks = {
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 2, 2 }, -- Improved Shadow Word: Pain
            { 3, 2, 2 }, -- Improved Shadow Word: Pain
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 3 }, -- Mind Flay
            { 3, 4, 3 }, -- Shadow Reach
            { 3, 4, 3 }, -- Shadow Reach
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 5, 2 }, -- Vampiric Embrace
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 7, 2 }, -- Shadowform
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 2, 3 }, -- Improved Power Word: Shield
            { 1, 2, 3 }, -- Improved Power Word: Shield
            { 1, 2, 3 }, -- Improved Power Word: Shield
            { 3, 2, 1 }, -- Shadow Affinity
            { 3, 2, 1 }, -- Shadow Affinity
            { 3, 2, 1 }, -- Shadow Affinity
            { 3, 3, 1 }, -- Improved Psychic Scream
            { 3, 3, 1 }, -- Improved Psychic Scream
            { 3, 4, 2 }, -- Improved Fade
            { 3, 4, 2 }, -- Improved Fade
            { 3, 5, 1 }, -- Silence
            { 3, 5, 3 }, -- Improved Vampiric Embrace
            { 3, 5, 3 }, -- Improved Vampiric Embrace
            { 3, 5, 4 }, -- Focused Mind
            { 3, 5, 4 }, -- Focused Mind
            { 3, 5, 4 }, -- Focused Mind
            { 3, 6, 1 }, -- Shadow Resilience
            { 3, 6, 1 }, -- Shadow Resilience
            { 3, 7, 3 }, -- Shadow Power
        },
    },
    SHAMAN = {
        spec = "Enhancement",
        picks = {
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 3 }, -- Improved Ghost Wolf
            { 2, 2, 3 }, -- Improved Ghost Wolf
            { 2, 3, 1 }, -- Enhancing Totems
            { 2, 3, 1 }, -- Enhancing Totems
            { 2, 3, 4 }, -- Anticipation
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 5, 3 }, -- Elemental Weapons
            { 2, 5, 3 }, -- Elemental Weapons
            { 2, 5, 3 }, -- Elemental Weapons
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 6, 4 }, -- Weapon Mastery
            { 2, 6, 4 }, -- Weapon Mastery
            { 2, 6, 4 }, -- Weapon Mastery
            { 2, 7, 3 }, -- Stormstrike
            { 2, 6, 4 }, -- Weapon Mastery
            { 2, 6, 4 }, -- Weapon Mastery
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 2, 2, 1 }, -- Guardian Totems
            { 2, 2, 1 }, -- Guardian Totems
            { 2, 2, 4 }, -- Improved Lightning Shield
            { 2, 2, 4 }, -- Improved Lightning Shield
            { 2, 2, 4 }, -- Improved Lightning Shield
            { 2, 3, 3 }, -- Shamanistic Focus
            { 2, 5, 1 }, -- Improved Weapon Totems
            { 2, 5, 1 }, -- Improved Weapon Totems
            { 2, 5, 2 }, -- Spirit Weapons
            { 2, 6, 1 }, -- Mental Quickness
            { 2, 6, 1 }, -- Mental Quickness
            { 2, 6, 1 }, -- Mental Quickness
            { 2, 7, 2 }, -- Dual Wield
        },
    },
    MAGE = {
        spec = "Frost",
        picks = {
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 3 }, -- Elemental Precision
            { 3, 1, 3 }, -- Elemental Precision
            { 3, 1, 3 }, -- Elemental Precision
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 3 }, -- Improved Frost Nova
            { 3, 2, 3 }, -- Improved Frost Nova
            { 3, 2, 4 }, -- Permafrost
            { 3, 2, 4 }, -- Permafrost
            { 3, 2, 4 }, -- Permafrost
            { 3, 3, 1 }, -- Piercing Ice
            { 3, 3, 1 }, -- Piercing Ice
            { 3, 3, 1 }, -- Piercing Ice
            { 3, 5, 2 }, -- Cold Snap
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 2 }, -- Frost Channeling
            { 3, 4, 2 }, -- Frost Channeling
            { 3, 4, 2 }, -- Frost Channeling
            { 3, 5, 3 }, -- Improved Cone of Cold
            { 3, 5, 3 }, -- Improved Cone of Cold
            { 3, 5, 3 }, -- Improved Cone of Cold
            { 3, 7, 2 }, -- Ice Barrier
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 1, 1, 1 }, -- Arcane Subtlety
            { 1, 1, 1 }, -- Arcane Subtlety
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 3 }, -- Improved Arcane Missiles
            { 1, 1, 3 }, -- Improved Arcane Missiles
            { 1, 1, 3 }, -- Improved Arcane Missiles
            { 1, 1, 3 }, -- Improved Arcane Missiles
            { 1, 1, 3 }, -- Improved Arcane Missiles
            { 3, 1, 1 }, -- Frost Warding
            { 3, 1, 1 }, -- Frost Warding
            { 3, 2, 2 }, -- Frostbite
            { 3, 2, 2 }, -- Frostbite
            { 3, 2, 2 }, -- Frostbite
            { 3, 3, 2 }, -- Icy Veins
            { 3, 3, 4 }, -- Improved Blizzard
            { 3, 3, 4 }, -- Improved Blizzard
            { 3, 3, 4 }, -- Improved Blizzard
            { 3, 4, 1 }, -- Arctic Reach
        },
    },
    WARLOCK = {
        spec = "Affliction",
        picks = {
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 2, 3 }, -- Improved Life Tap
            { 1, 2, 3 }, -- Improved Life Tap
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 4, 2 }, -- Nightfall
            { 1, 4, 2 }, -- Nightfall
            { 1, 4, 1 }, -- Grim Reach
            { 1, 4, 1 }, -- Grim Reach
            { 1, 5, 2 }, -- Siphon Life
            { 1, 3, 3 }, -- Amplify Curse
            { 1, 3, 1 }, -- Improved Curse of Agony
            { 1, 3, 1 }, -- Improved Curse of Agony
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 7, 3 }, -- Dark Pact
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 2, 2 }, -- Improved Voidwalker
            { 2, 2, 2 }, -- Improved Voidwalker
            { 2, 2, 2 }, -- Improved Voidwalker
            { 2, 2, 3 }, -- Fel Intellect
            { 2, 2, 3 }, -- Fel Intellect
            { 2, 2, 3 }, -- Fel Intellect
            { 2, 3, 2 }, -- Fel Domination
            { 1, 2, 1 }, -- Improved Curse of Weakness
            { 1, 2, 1 }, -- Improved Curse of Weakness
            { 1, 2, 2 }, -- Improved Drain Soul
            { 1, 2, 2 }, -- Improved Drain Soul
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 4, 4 }, -- Empowered Corruption
            { 1, 4, 4 }, -- Empowered Corruption
            { 1, 4, 4 }, -- Empowered Corruption
            { 1, 5, 1 }, -- Shadow Embrace
            { 1, 5, 1 }, -- Shadow Embrace
            { 1, 5, 1 }, -- Shadow Embrace
            { 1, 5, 1 }, -- Shadow Embrace
            { 1, 5, 1 }, -- Shadow Embrace
            { 1, 5, 3 }, -- Curse of Exhaustion
            { 1, 7, 2 }, -- Contagion
            { 1, 7, 2 }, -- Contagion
            { 1, 7, 2 }, -- Contagion
        },
    },
    DRUID = {
        spec = "Feral Combat",
        picks = {
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 3 }, -- Thick Hide
            { 2, 2, 3 }, -- Thick Hide
            { 2, 2, 3 }, -- Thick Hide
            { 2, 3, 3 }, -- Sharpened Claws
            { 2, 3, 3 }, -- Sharpened Claws
            { 2, 3, 3 }, -- Sharpened Claws
            { 2, 3, 2 }, -- Feral Charge
            { 2, 4, 2 }, -- Predatory Strikes
            { 2, 4, 2 }, -- Predatory Strikes
            { 2, 4, 2 }, -- Predatory Strikes
            { 2, 4, 3 }, -- Primal Fury
            { 2, 4, 3 }, -- Primal Fury
            { 2, 5, 1 }, -- Savage Fury
            { 2, 5, 1 }, -- Savage Fury
            { 2, 5, 3 }, -- Faerie Fire (Feral)
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 7, 2 }, -- Leader of the Pack
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 2, 2 }, -- Brutal Impact
            { 2, 2, 2 }, -- Brutal Impact
            { 2, 3, 1 }, -- Feral Swiftness
            { 2, 3, 1 }, -- Feral Swiftness
            { 2, 4, 1 }, -- Shredding Attacks
            { 2, 4, 1 }, -- Shredding Attacks
            { 2, 5, 4 }, -- Nurturing Instinct
            { 2, 5, 4 }, -- Nurturing Instinct
            { 2, 6, 3 }, -- Survival of the Fittest
            { 2, 6, 3 }, -- Survival of the Fittest
            { 2, 6, 3 }, -- Survival of the Fittest
            { 2, 7, 1 }, -- Primal Tenacity
            { 2, 7, 1 }, -- Primal Tenacity
            { 2, 7, 1 }, -- Primal Tenacity
            { 2, 7, 3 }, -- Improved Leader of the Pack
            { 2, 7, 3 }, -- Improved Leader of the Pack
            { 2, 8, 3 }, -- Predatory Instincts
        },
    },
}
