-- Generated by `fg talents` from the game's talent trees. Do not edit.
-- One talent per level from 10: { tab, tier, column } (1-based, as GetTalentInfo).
local _, FG = ...
FG.TalentBuilds = FG.TalentBuilds or {}
FG.TalentBuilds.forever = {
    WARRIOR = {
        spec = "Arms",
        picks = {
            { 1, 1, 1 }, -- Improved Heroic Strike
            { 1, 1, 1 }, -- Improved Heroic Strike
            { 1, 1, 1 }, -- Improved Heroic Strike
            { 1, 1, 3 }, -- Improved Rend
            { 1, 1, 3 }, -- Improved Rend
            { 1, 2, 2 }, -- Improved Tactical Mastery
            { 1, 2, 2 }, -- Improved Tactical Mastery
            { 1, 2, 2 }, -- Improved Tactical Mastery
            { 1, 2, 2 }, -- Improved Tactical Mastery
            { 1, 2, 2 }, -- Improved Tactical Mastery
            { 1, 1, 3 }, -- Improved Rend
            { 1, 3, 1 }, -- Improved Overpower
            { 1, 3, 1 }, -- Improved Overpower
            { 1, 3, 2 }, -- Anger Management
            { 1, 3, 3 }, -- Deep Wounds
            { 1, 3, 3 }, -- Deep Wounds
            { 1, 3, 3 }, -- Deep Wounds
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 2 }, -- Two-Handed Weapon Specialization
            { 1, 4, 3 }, -- Impale
            { 1, 4, 3 }, -- Impale
            { 1, 5, 2 }, -- Sweeping Strikes
            { 1, 5, 4 }, -- Weaponmaster
            { 1, 5, 4 }, -- Weaponmaster
            { 1, 5, 4 }, -- Weaponmaster
            { 1, 5, 4 }, -- Weaponmaster
            { 1, 5, 4 }, -- Weaponmaster
            { 1, 5, 3 }, -- Weaponmaster
            { 1, 5, 3 }, -- Weaponmaster
            { 1, 5, 3 }, -- Weaponmaster
            { 1, 5, 3 }, -- Weaponmaster
            { 1, 5, 3 }, -- Weaponmaster
            { 1, 5, 1 }, -- Weaponmaster
            { 1, 5, 1 }, -- Weaponmaster
            { 1, 5, 1 }, -- Weaponmaster
            { 1, 5, 1 }, -- Weaponmaster
            { 1, 5, 1 }, -- Weaponmaster
            { 1, 7, 2 }, -- Mortal Strike
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 1, 3 }, -- Cruelty
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
            { 2, 2, 3 }, -- Unbridled Wrath
        },
    },
    PALADIN = {
        spec = "Retribution",
        picks = {
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 1, 3 }, -- Benediction
            { 3, 2, 1 }, -- Improved Judgement
            { 3, 2, 1 }, -- Improved Judgement
            { 3, 2, 2 }, -- Improved Seal of the Crusader
            { 3, 2, 2 }, -- Improved Seal of the Crusader
            { 3, 2, 2 }, -- Improved Seal of the Crusader
            { 3, 3, 3 }, -- Seal of Command
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 2, 3 }, -- Deflection
            { 3, 3, 1 }, -- Vindication
            { 3, 3, 1 }, -- Vindication
            { 3, 3, 1 }, -- Vindication
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 2 }, -- Conviction
            { 3, 3, 4 }, -- Pursuit of Justice
            { 3, 3, 4 }, -- Pursuit of Justice
            { 3, 5, 1 }, -- Two-Handed Weapon Specialization
            { 3, 5, 1 }, -- Two-Handed Weapon Specialization
            { 3, 5, 1 }, -- Two-Handed Weapon Specialization
            { 3, 5, 3 }, -- Sanctity Aura
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 6, 2 }, -- Vengeance
            { 3, 7, 2 }, -- Repentance
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 2 }, -- Divine Strength
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 1, 1, 3 }, -- Divine Intellect
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
            { 3, 1, 2 }, -- Improved Blessing of Might
        },
    },
    HUNTER = {
        spec = "Beast Mastery",
        picks = {
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 1, 3 }, -- Endurance Training
            { 1, 2, 3 }, -- Thick Hide
            { 1, 2, 3 }, -- Thick Hide
            { 1, 2, 3 }, -- Thick Hide
            { 1, 2, 4 }, -- Improved Revive Pet
            { 1, 2, 4 }, -- Improved Revive Pet
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 3, 3 }, -- Unleashed Fury
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 4, 3 }, -- Ferocity
            { 1, 5, 1 }, -- Spirit Bond
            { 1, 5, 1 }, -- Spirit Bond
            { 1, 5, 2 }, -- Intimidation
            { 1, 5, 4 }, -- Bestial Discipline
            { 1, 5, 4 }, -- Bestial Discipline
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 6, 3 }, -- Frenzy
            { 1, 7, 2 }, -- Bestial Wrath
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 2, 1, 2 }, -- Improved Concussive Shot
            { 1, 1, 2 }, -- Deadly Aspects
            { 1, 1, 2 }, -- Deadly Aspects
            { 1, 1, 2 }, -- Deadly Aspects
            { 1, 1, 2 }, -- Deadly Aspects
            { 1, 1, 2 }, -- Deadly Aspects
            { 1, 2, 1 }, -- Improved Eyes of the Beast
            { 1, 2, 1 }, -- Improved Eyes of the Beast
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 2, 2 }, -- Improved Aspect of the Monkey
            { 1, 3, 1 }, -- Pathfinding
            { 1, 3, 1 }, -- Pathfinding
            { 1, 3, 2 }, -- Bestial Swiftness
        },
    },
    ROGUE = {
        spec = "Combat",
        picks = {
            { 2, 1, 2 }, -- Improved Sinister Strike
            { 2, 1, 2 }, -- Improved Sinister Strike
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 1, 3 }, -- Lightning Reflexes
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 2, 2, 3 }, -- Precision
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 1, 3 }, -- Malice
            { 1, 2, 4 }, -- Improved Slice and Dice
            { 1, 2, 4 }, -- Improved Slice and Dice
            { 1, 2, 4 }, -- Improved Slice and Dice
            { 1, 2, 1 }, -- Ruthlessness
            { 1, 2, 1 }, -- Ruthlessness
            { 1, 2, 1 }, -- Ruthlessness
            { 1, 3, 1 }, -- Relentless Strikes
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 3, 3 }, -- Lethality
            { 1, 1, 1 }, -- Improved Eviscerate
            { 1, 1, 1 }, -- Improved Eviscerate
            { 1, 1, 1 }, -- Improved Eviscerate
            { 2, 1, 1 }, -- Improved Gouge
            { 2, 1, 1 }, -- Improved Gouge
            { 2, 1, 1 }, -- Improved Gouge
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 4, 3 }, -- Dual Wield Specialization
            { 2, 5, 2 }, -- Blade Flurry
            { 2, 2, 1 }, --
            { 2, 2, 1 }, --
            { 2, 2, 1 }, --
            { 2, 2, 2 }, -- Deflection
            { 2, 6, 2 }, -- Weapon Expertise
            { 2, 6, 2 }, -- Weapon Expertise
            { 2, 6, 3 }, -- Aggression
            { 2, 6, 3 }, -- Aggression
            { 2, 6, 3 }, -- Aggression
            { 2, 7, 2 }, -- Adrenaline Rush
        },
    },
    PRIEST = {
        spec = "Shadow",
        picks = {
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 1, 2 }, -- Spirit Tap
            { 3, 2, 2 }, -- Improved Shadow Word: Pain
            { 3, 2, 2 }, -- Improved Shadow Word: Pain
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 2, 3 }, -- Shadow Focus
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 2 }, -- Improved Mind Blast
            { 3, 3, 3 }, -- Mind Flay
            { 3, 4, 3 }, -- Shadow Reach
            { 3, 4, 3 }, -- Shadow Reach
            { 3, 4, 3 }, -- Shadow Reach
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 4, 4 }, -- Shadow Weaving
            { 3, 5, 2 }, -- Vampiric Embrace
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 6, 3 }, -- Darkness
            { 3, 7, 2 }, -- Shadowform
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 3, 1, 3 }, -- Blackout
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 1, 3 }, -- Wand Specialization
            { 1, 2, 3 }, -- Improved Power Word: Shield
            { 1, 2, 3 }, -- Improved Power Word: Shield
            { 1, 2, 3 }, -- Improved Power Word: Shield
            { 3, 2, 1 }, -- Shadow Affinity
            { 3, 2, 1 }, -- Shadow Affinity
            { 3, 2, 1 }, -- Shadow Affinity
            { 3, 3, 1 }, -- Improved Psychic Scream
            { 3, 3, 1 }, -- Improved Psychic Scream
        },
    },
    SHAMAN = {
        spec = "Enhancement",
        picks = {
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 1, 2 }, -- Ancestral Knowledge
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 2 }, -- Thundering Strikes
            { 2, 2, 3 }, -- Improved Ghost Wolf
            { 2, 2, 3 }, -- Improved Ghost Wolf
            { 2, 3, 3 }, -- Two-Handed Axes and Maces
            { 2, 3, 1 }, -- Enhancing Totems
            { 2, 3, 1 }, -- Enhancing Totems
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 4, 2 }, -- Flurry
            { 2, 5, 2 }, -- Elemental Weapons
            { 2, 5, 2 }, -- Elemental Weapons
            { 2, 5, 2 }, -- Elemental Weapons
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 3, 4 }, -- Anticipation
            { 2, 6, 3 }, -- Weapon Mastery
            { 2, 6, 3 }, -- Weapon Mastery
            { 2, 7, 2 }, -- Stormstrike
            { 2, 6, 3 }, -- Weapon Mastery
            { 2, 6, 3 }, -- Weapon Mastery
            { 2, 6, 3 }, -- Weapon Mastery
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 1, 3 }, -- Shield Specialization
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 2, 4, 3 }, -- Toughness
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 1, 1, 2 }, -- Convection
            { 2, 2, 1 }, -- Guardian Totems
            { 2, 2, 1 }, -- Guardian Totems
        },
    },
    MAGE = {
        spec = "Frost",
        picks = {
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 2 }, -- Improved Frostbolt
            { 3, 1, 3 }, -- Elemental Precision
            { 3, 1, 3 }, -- Elemental Precision
            { 3, 1, 3 }, -- Elemental Precision
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 1 }, -- Ice Shards
            { 3, 2, 3 }, -- Improved Frost Nova
            { 3, 2, 3 }, -- Improved Frost Nova
            { 3, 2, 4 }, -- Permafrost
            { 3, 2, 4 }, -- Permafrost
            { 3, 2, 4 }, -- Permafrost
            { 3, 3, 1 }, -- Piercing Ice
            { 3, 3, 1 }, -- Piercing Ice
            { 3, 3, 1 }, -- Piercing Ice
            { 3, 3, 2 }, -- Cold Snap
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 3 }, -- Shatter
            { 3, 4, 2 }, -- Frost Channeling
            { 3, 4, 2 }, -- Frost Channeling
            { 3, 4, 2 }, -- Frost Channeling
            { 3, 5, 2 }, -- Ice Block
            { 3, 5, 3 }, -- Improved Cone of Cold
            { 3, 5, 3 }, -- Improved Cone of Cold
            { 3, 5, 3 }, -- Improved Cone of Cold
            { 3, 7, 2 }, -- Ice Barrier
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 3, 6, 3 }, -- Winter's Chill
            { 1, 1, 1 }, -- Arcane Subtlety
            { 1, 1, 1 }, -- Arcane Subtlety
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 1, 1, 2 }, -- Arcane Focus
            { 3, 1, 1 }, -- Frost Warding
            { 3, 1, 1 }, -- Frost Warding
            { 3, 2, 2 }, -- Frostbite
            { 3, 2, 2 }, -- Frostbite
        },
    },
    WARLOCK = {
        spec = "Affliction",
        picks = {
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 3 }, -- Improved Corruption
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 1, 2 }, -- Suppression
            { 1, 2, 3 }, -- Improved Life Tap
            { 1, 2, 3 }, -- Improved Life Tap
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 3, 2 }, -- Fel Concentration
            { 1, 4, 2 }, -- Nightfall
            { 1, 4, 2 }, -- Nightfall
            { 1, 4, 1 }, -- Grim Reach
            { 1, 4, 1 }, -- Grim Reach
            { 1, 5, 2 }, -- Siphon Life
            { 1, 3, 3 }, -- Amplify Curse
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 1, 3 }, -- Demonic Embrace
            { 2, 2, 2 }, -- Improved Voidwalker
            { 2, 2, 2 }, -- Improved Voidwalker
            { 2, 2, 2 }, -- Improved Voidwalker
            { 1, 2, 1 }, -- Improved Curse of Weakness
            { 1, 2, 1 }, -- Improved Curse of Weakness
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 6, 2 }, -- Shadow Mastery
            { 1, 2, 1 }, -- Improved Curse of Weakness
            { 1, 2, 2 }, --
            { 1, 2, 2 }, --
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 2, 4 }, -- Soul Siphon
            { 1, 3, 1 }, -- Improved Bane of Agony
            { 1, 3, 1 }, -- Improved Bane of Agony
            { 1, 3, 1 }, -- Improved Bane of Agony
            { 1, 4, 4 }, --
            { 1, 4, 4 }, --
        },
    },
    DRUID = {
        spec = "Feral Combat",
        picks = {
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 1, 2 }, -- Ferocity
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 1 }, -- Feral Instinct
            { 2, 2, 3 }, -- Thick Hide
            { 2, 2, 3 }, -- Thick Hide
            { 2, 2, 3 }, -- Thick Hide
            { 2, 2, 3 }, -- Thick Hide
            { 2, 2, 3 }, -- Thick Hide
            { 2, 3, 3 }, -- Sharpened Claws
            { 2, 3, 3 }, -- Sharpened Claws
            { 2, 3, 3 }, -- Sharpened Claws
            { 2, 4, 2 }, -- Predatory Strikes
            { 2, 4, 2 }, -- Predatory Strikes
            { 2, 4, 2 }, -- Predatory Strikes
            { 2, 4, 4 }, -- Blood Frenzy
            { 2, 4, 4 }, -- Blood Frenzy
            { 2, 5, 1 }, -- Savage Fury
            { 2, 5, 1 }, -- Savage Fury
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 6, 2 }, -- Heart of the Wild
            { 2, 7, 2 }, -- Leader of the Pack
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 3 }, -- Furor
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 3, 1, 2 }, -- Improved Mark of the Wild
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 1, 3 }, -- Feral Aggression
            { 2, 2, 2 }, -- Brutal Impact
            { 2, 2, 2 }, -- Brutal Impact
            { 2, 3, 1 }, -- Feral Swiftness
            { 2, 3, 1 }, -- Feral Swiftness
            { 2, 3, 2 }, -- Feral Charge (Bear)
        },
    },
}
